using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using FourthDevs.Common;
using Newtonsoft.Json.Linq;

namespace FourthDevs.ContextAgent.Memory
{
    internal static class Observer
    {
        private const string SystemPrompt =
            "You are the memory consciousness of an AI assistant.\n" +
            "Your observations will be the ONLY information the assistant has about past interactions.\n\n" +
            "Extract high-fidelity observations from conversation history.\n" +
            "Do not chat. Do not explain. Output only structured XML.\n\n" +
            "Rules:\n" +
            "1) Every observation MUST be tagged with its source: [user], [assistant], or [tool:name].\n" +
            "   - [user]: facts, preferences, decisions explicitly stated by the user.\n" +
            "   - [assistant]: actions taken, commitments made, or content generated by the assistant.\n" +
            "   - [tool:name]: outcomes of tool calls (e.g. [tool:write_file], [tool:read_file]).\n" +
            "2) Priority markers:\n" +
            "   - \U0001f534 high: explicit user facts, preferences, decisions, completed goals.\n" +
            "   - \U0001f7e1 medium: active work, project details, tool outcomes, unresolved blockers.\n" +
            "   - \U0001f7e2 low: tentative or minor details, assistant elaborations.\n" +
            "3) Preserve concrete details: names, numbers, dates, file paths, quoted phrasing.\n" +
            "4) Capture state changes explicitly (\"updating previous preference\").\n" +
            "5) Keep observations concise but information-dense.\n" +
            "6) Do NOT repeat observations that already exist in previous observations.\n\n" +
            "Output format (strict):\n" +
            "<observations>\n" +
            "* \U0001f534 [user] ...\n" +
            "* \U0001f7e1 [assistant] ...\n" +
            "* \U0001f7e1 [tool:write_file] ...\n" +
            "</observations>\n\n" +
            "<current-task>\n" +
            "Primary: ...\n" +
            "</current-task>\n\n" +
            "<suggested-response>\n" +
            "...\n" +
            "</suggested-response>";

        public static async Task<ObserverResult> RunAsync(
            List<JObject> messages,
            string previousObservations)
        {
            string serialized = SerializeMessages(messages);
            string prevObs = string.IsNullOrEmpty(previousObservations) ? "[none]" : previousObservations;

            string userPrompt =
                "## Previous Observations\n\n" +
                prevObs +
                "\n\n---\n\nDo not repeat these existing observations. Only extract new ones.\n\n" +
                "## New Message History\n\n" +
                serialized +
                "\n\n---\n\nExtract new observations. Return only XML with <observations>, <current-task>, <suggested-response>.";

            string model = AiConfig.ResolveModel(MemoryConfig.ObserverModel);
            string response = await CallLlmAsync(model, SystemPrompt, userPrompt).ConfigureAwait(false);

            string observations = ExtractTag(response, "observations");
            string currentTask = ExtractTag(response, "current-task");

            return new ObserverResult
            {
                Observations = observations ?? string.Empty,
                CurrentTask = currentTask ?? string.Empty,
                RawResponse = response
            };
        }

        private static string SerializeMessages(List<JObject> messages)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < messages.Count; i++)
            {
                var msg = messages[i];
                string type = (string)msg["type"] ?? (string)msg["role"];
                int idx = i + 1;

                if (type == "function_call")
                {
                    string name = (string)msg["name"] ?? "";
                    string args = Truncate((string)msg["arguments"] ?? "", 3000);
                    sb.AppendFormat("**Assistant Tool Call (#{0}):**\n[Tool: {1}] {2}\n\n", idx, name, args);
                }
                else if (type == "function_call_output")
                {
                    string output = Truncate((string)msg["output"] ?? "", 3000);
                    sb.AppendFormat("**Tool Result (#{0}):**\n{1}\n\n", idx, output);
                }
                else
                {
                    string role = (string)msg["role"] ?? type;
                    string content = GetContent(msg);
                    content = Truncate(content, 6000);
                    string label = role == "user" ? "User" : "Assistant";
                    sb.AppendFormat("**{0} (#{1}):**\n{2}\n\n", label, idx, content);
                }
            }
            return sb.ToString();
        }

        private static string GetContent(JObject msg)
        {
            var contentToken = msg["content"];
            if (contentToken == null) return "";
            if (contentToken.Type == JTokenType.String) return (string)contentToken;
            if (contentToken.Type == JTokenType.Array)
            {
                var arr = (JArray)contentToken;
                foreach (var item in arr)
                {
                    if ((string)item["type"] == "output_text")
                        return (string)item["text"] ?? "";
                    if (item["text"] != null)
                        return (string)item["text"] ?? "";
                }
            }
            return contentToken.ToString();
        }

        private static string Truncate(string s, int max)
        {
            if (s == null) return "";
            return s.Length <= max ? s : s.Substring(0, max) + "\u2026";
        }

        private static string ExtractTag(string text, string tag)
        {
            var match = Regex.Match(text, string.Format("<{0}>(.*?)</{0}>", tag),
                RegexOptions.Singleline | RegexOptions.IgnoreCase);
            return match.Success ? match.Groups[1].Value.Trim() : null;
        }

        private static async Task<string> CallLlmAsync(string model, string system, string user)
        {
            var inputMessages = new JArray
            {
                new JObject { ["type"] = "message", ["role"] = "user", ["content"] = user }
            };

            var body = new JObject
            {
                ["model"] = model,
                ["instructions"] = system,
                ["input"] = inputMessages,
                ["store"] = false
            };

            return await LlmClient.PostAsync(body).ConfigureAwait(false);
        }
    }

    internal class ObserverResult
    {
        public string Observations { get; set; }
        public string CurrentTask { get; set; }
        public string RawResponse { get; set; }
    }
}
